[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]] #toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'gosukiwi/vim-atom-dark'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'zchee/deoplete-go'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'thinca/vim-quickrun'

#[[plugins]]
#repo = 'zchee/nvim-go'
#build = 'make'

# 括弧自動閉じ
[[plugins]]
repo = 'Townk/vim-autoclose'

# Dockerfileシンタックス
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

# Git差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Vue シンタックス
[[plugins]]
repo = 'posva/vim-vue'

# js シンタックス
[[plugins]]
repo = 'jelera/vim-javascript-syntax'

#html/css
[[plugins]]
repo = "mattn/emmet-vim"

#NERDtree
[[plugins]]
repo = 'scrooloose/nerdtree'

#js 補完
[[plugins]]
repo = 'marijnh/tern_for_vim'

[[plugins]]
repo = 'hokaccha/vim-html5validator'
