[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]] #toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'neomake/neomake'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'

#python deoplete
#[[plugins]]
#repo = 'davidhalter/jedi-vim'

# 括弧自動閉じ, 括弧時の自動インデント
[[plugins]]
repo = 'cohama/lexima.vim'

# Dockerfileシンタックス
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

# Git差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Vue シンタックス
[[plugins]]
repo = 'posva/vim-vue'

#NERDtree
[[plugins]]
repo = 'scrooloose/nerdtree'

# edit-config
[[plugins]]
repo='editorconfig/editorconfig-vim'

#vim-node
[[plugins]]
repo='moll/vim-node'

# fish-syntax
[[plugins]]
repo='dag/vim-fish'

[[plugins]]
repo = "pangloss/vim-javascript"

[[plugins]]
repo = "mattn/jscomplete-vim"
for = 'javascript'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
